services:
  searxng:
    image: searxng/searxng
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./docker/searxng/config:/etc/searxng
      - ./docker/searxng/data:/var/cache/searxng
